name: "Test typescript-action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
      with: 
        text: "test"
        file: "test1.txt"
    - uses: ./
      with: 
        text: "dGVzdA=="
        file: "test2.txt"
        encoding: "base64"
    - run: cat test1.txt
    - run: cat test2.txt

    - name: Secret
      uses: ./
      with: 
        text: ${{ secrets.SECRET_KEY }}
        file: "/github/runner/.test/test"
    - run: cat $HOME/.test/test
